language: python
python:
- '3.6'
env:
  global:
  - secure: pGBNyKpBo5zHPiGvfEyVaDys9F1xOgnB8MX9437dAYUcfha10i6yDF9irVk/1ekuug2cXjSMObVaZjlk/j7Q/eXkLlwH3mcFZ1+nkbh0wFJM4m55eDqeqV1Hw42/XI7XmkIErPROowK5jkIgz4JrArGLx1OROJG5cCk1TfA77iDLwU45fEk5KqQNRcNo2UaH3DMfxRoznIqwBSPFvkz1BvqA6VNceFYfG2lc/E/bKb7wrI7fkXKRmAgPr+IYx7i0gnhgApS+jTpsTdVXqslqgnSKMgNQqllUQEyzrRn+f8jCBO6zdq9qaT9DMNtBTYSwrYMY5BWHEpR0TWAkth1aCeJxepJE1PNnmdurRNHAjKzrFLQy9YiQs9lvktaVSfeTYBHTa+lKklrpfGC/U785hQQ3jGpCN7vW5bkZvgQr3TghLUCjib29BwhHXGgP8DhDi+j2Z9zRsfZ9tBCO66tXR6ZMEkDuU1gDYJSZg/+J820hTOlc//huLICU3F0gg3MLom2FtwknS6QM7UMOW9ikpjI9Ou9vhmScjX8f0gmBRJE+SomIRUJLrzBAV9m20oDDUsruKs6AHvyz1FU3yZJVAmKlnihFTvmqhj825AYBYe/FBYyFs54rgF7QIkFHcOIBkwJ7dtiOvrtD7t+yC/lo9Hv0tD8Q3uMEoGYiXNIVZQs=
  - secure: 8nB2nle/96S7U3GeRCqtG3egnTydtB8lLvBPrxJmV8XhDiz52TpYHzOHtI1bm9uXQlKORSp205HaKoZjUb2OQwp4d7TN6YfO1kg1sAQJZkHUmvt3bV/KDDeJ4lluCXoD7/uoTKu883FQBL7Zl5k8QXOacUhvtNjAzZl1NBT1Tr+QxIv1UCy73Uuw/3Ja9xYRFEkyjf07Kcppm2O6ioaXAfdEv4QBZ3p2WCP3tQ7H1gsHjWM0sqozuLr2fNEAqjOIRnDPMtvY3peZpIbDIJyd7YRWqqEbd2Mzd//AYTS/8jiVfpa+qs6NWhPf78OzG1qsRBNODE7Hx8wjcBV53eCkKgpw3ghwwSrZ/Nw2JlgLqGtL8nzd9Nejfnp4C9whBA59tTESIURv6PpfhM2zA35vRu1XOe35V7kpczfG2yVtOnup0UD/umtYfWjEAPPuDNXytvPHB1wykN07R05+2A8D32BXi20pZh7JjO2NJ3+bh4I/5g2lKJcBaakJJDxqy3P/Roa5NjvPbtEad3SQ3H6xUCoxxxfjaB0b9MDqkJ1OB5W1LbpxPuWNmJJcMDUzKbyMHlKgZ+21zUCChux4kCDaNHMx1ETfOQF7ZKR9ewikYblXX9t5zi210vIK3KKTsB/LBX004xF29R/bVJKVJnxlqYnhCjlBbEhO5t59vsRG4og=
install:
- pip install flake8
script:
- flake8 prometheus.py
- docker build -t vaping-exporter:$TRAVIS_BUILD_NUMBER .
- docker tag vaping-exporter:$TRAVIS_BUILD_NUMBER vaping-exporter:latest
after_success:
- |
  # This is a master build, build and push our docker image.
  if [ "x$TRAVIS_BRANCH" == "xmaster" ] && [ "x$TRAVIS_PULL_REQUEST" == "xfalse" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    docker tag vaping-exporter:$TRAVIS_BUILD_NUMBER brajkovic/vaping-exporter:$TRAVIS_BUILD_NUMBER
    docker push brajkovic/vaping-exporter:$TRAVIS_BUILD_NUMBER
    docker tag vaping-exporter:latest brajkovic/vaping-exporter:latest
    docker push brajkovic/vaping-exporter:latest
  fi
